### ISSUE TITLE
Ok idk if i wanna call this a bug or it still in development

### ISSUE THREAD

**Issue by Ravienc** [KlavierGayming/FNF-Micd-Up-Mobile#12]
Ok so the first bug is when i play the pico week its lagging even on the other week is not,
And the second bug/in development thing is the last agoti song the backrounds is from week 1
Ok thanks

**Comment by moondroidcoder** [comment]
Pico week lagging is not a bug, take a look at your ram peak at topright,  and agoti is still in development
