### ISSUE TITLE
Chart Can't Move (Bug)

### ISSUE THREAD

**Issue by brayangd0** [KlavierGayming/FNF-Micd-Up-Mobile#19]
I Can't Move In Chart
![Capture 2021-05-30 23 42 23](https://user-images.githubusercontent.com/84863814/120132664-26378400-c1a1-11eb-892a-ae14bd5a037d.jpg)
( ScreenShot On My Editor )

**Comment by moondroidcoder** [comment]
The reason you cant move in chart is cuz we havent coded it in. Yes we fixed it but we didnt push the update yet. Closing

**Comment by brayangd0** [comment]
Ok, Thx
