### ISSUE TITLE
Question: why this isn't in the game

### ISSUE THREAD

**Issue by ega54** [KlavierGayming/FNF-Micd-Up-Mobile#25]
I found this in the file while I checked the APK with APK Editor
![Screenshot_20210608_184649](https://user-images.githubusercontent.com/85556215/121176132-7348e380-c88e-11eb-8662-4f51f3905e06.jpg)
And it actually use for the debug menu so I downloaded the game and then it never show up 
![Screenshot_20210608_184724](https://user-images.githubusercontent.com/85556215/121176607-fbc78400-c88e-11eb-9e4d-17420a5927d4.jpg)
Sooooo are you gonna add that for the debug menu

**Comment by KlavierGayming** [comment]
that is used for the character offset menu. You can find it in the options. Closing.
