### ISSUE TITLE
Not finishing the Download 

### ISSUE THREAD

**Issue by nisomio** [KlavierGayming/FNF-Micd-Up-Mobile#5]
I'm downloading the latest release on Android chrome and it's stuck on 100% before this I also tried downloading the other builds from Zack's videos and luckydog's 
![IMG_20210529_111909](https://user-images.githubusercontent.com/84639321/120065142-2be17c80-c070-11eb-8a9e-69e8af285dd1.jpg)

**Comment by nisomio** [comment]
So I tried making the APK myself because I had the files it was just that chrome wasn't installing but... "App not installed" it even had the icon and the name, I checked the files they were all there and my phone released last year

**Comment by moondroidcoder** [comment]
Im sorry but you might have to
Clear your storage and cache
Clear cache of google chrome
And make sure internet is atleast ok at all times

**Comment by nisomio** [comment]
> Im sorry but you might have to
> Clear your storage and cache
> Clear cache of google chrome
> And make sure internet is atleast ok at all times


Still doesn't work
![IMG_20210529_162155](https://user-images.githubusercontent.com/84639321/120073759-fe112d80-c099-11eb-8659-fc0226bebcd9.jpg)

I just want to play, man

**Comment by moondroidcoder** [comment]
That error happens with chrome. Try checking your downloads folder, you might find the apk

**Comment by nisomio** [comment]
> That error happens with chrome. Try checking your downloads folder, you might find the apk

Nope can't find it, so I cancelled the download on chrome because I've been trying to download this and wasting internet

**Comment by nisomio** [comment]
> > That error happens with chrome. Try checking your downloads folder, you might find the apk
> 
> Nope can't find it, so I cancelled the download on chrome because I've been trying to download this and wasting internet


And also before downloading this today, I downloaded fnf HD and I found it in my downloads and it worked

**Comment by moondroidcoder** [comment]
Then idrk. Sorry bud
