### ISSUE TITLE
ELLO CAN YOU MAKE ONLY UPDATE FILE? 

### ISSUE THREAD

**Issue by Ravienc** [KlavierGayming/FNF-Micd-Up-Mobile#7]
CAN YOU MAKE ONLY UPDATE FILE SO I CAN NOT WASTE MY DATA CUZ I ALREADY DOWNLOAD THE PREVIOUS VERSION? 
Thanks

**Comment by KlavierGayming** [comment]
Ummm no
We edited code, not assets.

**Comment by KlavierGayming** [comment]
Closing.
