### ISSUE TITLE
2. After the first song on Agoti's week the game instantly crashes before the second song even starts.

### ISSUE THREAD

**Issue by AeOe** [KlavierGayming/FNF-Micd-Up-Mobile#9]
Probably just on my phone but most likely a bug, if it's not a bug. If possible optimize it since my phone also freezes on screenplay when it's boyfriend's first turn after Agoti then goes to normal after like 3-5 seconds.

**Comment by moondroidcoder** [comment]
Not a bug. Its just your phone

**Comment by AeOe** [comment]
Alright, the rest of the game was smooth so it was kinda suspicious. Sorry
for the trouble, also have a good day or night.
